### ISSUE TITLE
How can I open a New activity when you click an item?

### ISSUE THREAD

**Issue by pisoleto** [algolia/algolia-android-demo#4]
Hi! It could be great if the demo show how to open the new activity ( with their correspondent data ) when you click a item.
Thanks again!

**Comment by PLNech** [comment]
Hi @pisoleto, thanks for the suggestion! This is indeed a pattern that would be worth demonstrating.

We'll soon start a refactoring effort to make our android demos more impactful, I'll make sure then to consider this feature 🙂

**Comment by sverrirs** [comment]
:+1:  on this. Can you provide any hint on how to do this?

**Comment by PLNech** [comment]
Hi @sverrirs, sorry for the late reply!

Currently the most up to date demos for using Algolia on Android are our [InstantSearch Android Examples](https://github.com/algolia/instantsearch-android-examples). 

Using InstantSearch Android, reacting to clicks on a specific item is quite simple: 

```java
// Get a reference to your Hits widget
final Hits hits = findViewById(R.id.hits);

// Add an OnItemClickListener
hits.setOnItemClickListener(new ItemClickSupport.OnItemClickListener() {
    @Override
    public void onItemClick(RecyclerView recyclerView, int position, View v) {
        // Get the clicked hit
        final JSONObject object = hits.get(position);

        // Use the hit, e.g. to open a DetailsActivity that displays the item:
        new Intent(EcommerceActivity.this, DetailsActivity.class)
                .putExtra("itemJSON", object.toString());
    }
});
```

Let me know if this helps, and if you have further questions either reopen this issue if it's related or else open a new one :)

**Comment by sverrirs** [comment]
Merci Paul-Louis :)
